# Generated by Django 4.2.13 on 2024-07-20 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meals',
            name='meal_type',
            field=models.CharField(choices=[('Starter', 'St'), ('Main Course', 'Mc'), ('Dessert', 'Ds')], max_length=20, null=True),
        ),
    ]
