# Generated by Django 4.2.13 on 2024-07-20 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0002_meals_meal_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meals',
            name='meal_type',
            field=models.CharField(choices=[('Starter', 'Starter'), ('Main Course', 'Main Course'), ('Dessert', 'Dessert')], max_length=20, null=True),
        ),
    ]
