# Generated by Django 4.2.13 on 2024-07-22 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0003_alter_meals_meal_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meals',
            name='image',
            field=models.ImageField(upload_to='./static/assets'),
        ),
    ]
